name: GitHub Actions Dependable
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - master
jobs:
  Google-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google-Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run google1
          browser: chrome
          headless: true
          record: false
  Amazon-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: [Google-Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Amazon-Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run amazon
          browser: chrome
          headless: true
          record: false
