name: GitHub Actions Parallel Job
'on':
 
  workflow_dispatch: null
  pull_request:
    branches:
      - master
  push:
    branches:
      - master    
jobs:
  Google-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google-Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run google
          browser: chrome
          headless: true
          record: false
          
          
      - name: Upload Report1
        uses: actions/upload-artifact@v3
        with:
          name: k6-report-summary
          path: summary.html
     
  Amazon-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Amazon-Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run amazon
          browser: chrome
          headless: true
          record: false
          
      - name: Upload Report2
        uses: actions/upload-artifact@v3
        with:
          name: k6-report-summary
          path: summary.html
          
  combine-reports:
    needs: [Google-Test, Amazon-Test]
    runs-on: ubuntu-latest
    steps:
      - name: Download google report
        uses: actions/download-artifact@v2
        with:
          name: Upload Report1
      - name: Download Amazon report
        uses: actions/download-artifact@v2
        with:
          name: Upload Report2
      - name: Combine reports
        run: |
          # Combine the reports here
          echo "Reports combined"
        # Upload combined report as artifact
       
      - name: Upload combined report
        uses: actions/upload-artifact@v2
        with:
           name: combined-report
           path: test-report     
