name: GitHub Actions Parallel Job
'on':
 
  workflow_dispatch: null
  pull_request:
    branches:
      - master
  push:
    branches:
      - master    
jobs:
  Google-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google-Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run google
          browser: chrome
          headless: true
          record: false
          
          
      - name: Upload Report1
        uses: actions/upload-artifact@v3
        with:
          
          path: Test1.html
         
     
  Amazon-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Amazon-Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run amazon
          browser: chrome
          headless: true
          record: false
          
      - name: Upload Report2
        uses: actions/upload-artifact@v3
        with:
          
          path: Test2.html
         
          
  
