name: GitHub Actions Parallel Job with report
'on':
 
  workflow_dispatch: null
  pull_request:
    branches:
      - master
  push:
    branches:
      - master    
jobs:
  Google-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google-Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run google
          browser: chrome
         
          
      - name: Upload Report- Google
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report1
          path: cypress/reports/Result
          
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact1
          path: cypress/reports/Result
    
      
           
     
  Amazon-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Amazon-Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run amazon
          browser: chrome
         
          
      - name: Upload Report- Amazon
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report2
          path: cypress/reports/Result
          
          
          
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact2
          path: cypress/reports/Result    
   
  Merge-Test: 
    runs-on: ubuntu-latest
    steps:
     
      - name: Merge artifacts
        run: | 
             cat cypress/reports/Result cypress/reports/Result > cypress/reports/Result
  
      - name: Upload merged artifact
        uses: actions/upload-artifact@v2
        with:
         name: merged-artifact
         path: cypress/reports/Result

        

         
          
  
