name: GitHub Actions Parallel Job with report
'on':
 
  workflow_dispatch: null
  pull_request:
    branches:
      - master
  push:
    branches:
      - master    
jobs:
  Google-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google-Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run google
          browser: chrome
         
          
      - name: Upload Report- Google
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report1
          path: cypress/reports/Result
      
           
     
  Amazon-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Amazon-Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run amazon
          browser: chrome
         
          
      - name: Upload Report- Amazon
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report2
          path: cypress/reports/Result
          
  combine-reports:
    needs: [Google-Test, Amazon-Test]
    runs-on: ubuntu-latest
    steps:
      - name: Download google report
        uses: actions/download-artifact@v3
        with:
          name: HTML_Report1
      - name: Download Amazon report
        uses: actions/download-artifact@v3
        with:
          name: HTML_Report2
      - name: Combine reports
        run: |
          mkdir -p combined-artifacts
          zip -r combined-artifacts/artifacts.zip cypress/reports/Result cypress/reports/Result
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-artifacts
          path: combined-artifacts

           
        

         
          
  
